### ISSUE TITLE
Barcode scanner is not working

### ISSUE THREAD

**Issue by shelf-issues** [JTensai/shelf-issues#17]
Name: Jordan Taylor 
Email: football80@gmail.com 

It just seems to sit there scanning FOREVER

Auto collected this.$route information: 

name:			"pantry"
meta:			{"requiresAuth":true}
path:			"/pantry/SAvU9b1apzVI97Wmytpt"
hash:			""
query:			{}
params:			{"id":"SAvU9b1apzVI97Wmytpt"}
fullPath:		"/pantry/SAvU9b1apzVI97Wmytpt"
matched:		circular reference detected, could not stringify

**Comment by JTensai** [comment]
stupid dependency updates broke it some how.  tried to find out why, gave up after 2 hours.
