### ISSUE TITLE
Recipes ingredients don't have measurements showing up

### ISSUE THREAD

**Issue by shelf-issues** [JTensai/shelf-issues#18]
Name: Jordan Taylor 
Email: football80@gmail.com 

Try to add an ingredient to a recipe, it has no measurements available to select. I tried "Salted Butter"

Auto collected this.$route information: 

name:			"recipe_book"
meta:			{"requiresAuth":true}
path:			"/recipe_book/HGw75ZOPu5pMB79v9snE"
hash:			""
query:			{}
params:			{"id":"HGw75ZOPu5pMB79v9snE"}
fullPath:		"/recipe_book/HGw75ZOPu5pMB79v9snE"
matched:		circular reference detected, could not stringify

**Comment by JTensai** [comment]
Typo... fixed
