### ISSUE TITLE
Previously selected shopping list items get reselected when adding a new item to the list

### ISSUE THREAD

**Issue by shelf-issues** [JTensai/shelf-issues#19]
Name: Jordan Taylor 
Email: football80@gmail.com 

Select Items (tested with valid pantry items)
Deselect same items
Add a new item to the shopping list (used a custom item)

Actual: Old things get selected again
Expected: Selection does not change.

Auto collected this.$route information: 

name:			"shopping_lists"
meta:			{"requiresAuth":true}
path:			"/shopping_lists"
hash:			""
query:			{}
params:			{}
fullPath:		"/shopping_lists"
matched:		circular reference detected, could not stringify

**Comment by JTensai** [comment]
fixed it :D
